# Palette Forge generated Alacritty palette for Neo Sploosh Dark

[colors.primary]
background = "#212226"
foreground = "#f4f4f4"
dim_foreground = "#f4f4f4"
bright_foreground = "#f4f4f4"

[colors.cursor]
text = "#222222"
cursor = "#008DC9"

[colors.vi_mode_cursor]
text = "#222222"
cursor = "#008DC9"

[colors.selection]
text = "#F2F2F2"
background = "#2C2C2C"

[colors.search.matches]
foreground = "#222222"
background = "#008DC9"

[colors.search.focused_match]
foreground = "#222222"
background = "#2C2C2C"

[colors.footer_bar]
foreground = "#222222"
background = "#008DC9"

[colors.hints.start]
foreground = "#222222"
background = "#008DC9"

[colors.hints.end]
foreground = "#222222"
background = "#2C2C2C"

[colors.normal]
black = "#282828"
red = "#893151"
green = "#92bf38"
yellow = "#a4d149"
blue = "#008dc9"
magenta = "#48b7e7"
cyan = "#33acde"
white = "#e9e9e9"

[colors.bright]
black = "#595959"
red = "#a35b78"
green = "#b0db90"
yellow = "#b0db90"
blue = "#2ea5d7"
magenta = "#48b7e7"
cyan = "#33acde"
white = "#f8f8f8"

[[colors.indexed_colors]]
index = 16
color = "#008dc9"

[[colors.indexed_colors]]
index = 17
color = "#008dc9"
